blob_detector:
  base_link: "base_link"
  camera_link: "camera"

  filter_by_area: True
  min_area: 100
  max_area: 10000

  filter_by_color: True
  blob_color: 0

  filter_by_circularity: True
  min_circularity: 0.5
  max_circularity: 1.5