blob_detector:
  base_link: "camera"
  camera_link: "camera"

  radius_multiplier: 1
  min_threshold: 5
  max_threshold: 130
  
  filter_by_area: True
  min_area: 200
  max_area: 10000 

  filter_by_color: False 
  blob_color: 0

  filter_by_circularity: True
  min_circularity: 0
  max_circularity: 0.35

  filter_by_inertia: True
  min_inertia: 0.38
  max_inertia: 1

  filter_by_convexity: False
  min_convexity: 0.3
  max_convexity: 0.95
