blob_detector:
  base_link: "red/camera_link"
  camera_link: "red/camera_color_optical_frame"

  filter_by_area: True
  min_area: 100
  max_area: 100000

  filter_by_color: True
  blob_color: 0

  filter_by_circularity: True
  min_circularity: 0.5
  max_circularity: 1.5

  filter_by_inertia: True
  min_inertia: 0.5
  max_inertia: 1

  filter_by_convexity: True
  min_convexity: 0.9
  max_convexity: 1